### ISSUE TITLE
Specific file fails to process

### ISSUE THREAD

**Issue by RaghavRao** [Stanford-STAGES/stanford-stages#21]
Hi,

When trying to process [this file](https://www.dropbox.com/sh/e58owb5ireh72i9/AAB8mkNgc9vk-BpsiMq1ex-Pa?dl=0), I get the following error:

```

2020-06-10 15:40:20.614745 | Predicting using: ac_rh_ls_lstm_01
Traceback (most recent call last):
  File "inf_narco_app.py", line 302, in <module>
    main(edfFile, jsonObj)
  File "inf_narco_app.py", line 124, in main
    print(narcoApp.get_diagnosis())
  File "inf_narco_app.py", line 185, in get_diagnosis
    prediction = self.get_narco_prediction()
  File "inf_narco_app.py", line 236, in get_narco_prediction
    X = self.get_hypnodensity_features(gpmodel, idx)
  File "inf_narco_app.py", line 218, in get_hypnodensity_features
    return self.Hypnodensity.get_features(modelName, idx)
  File "/home/raghav/Development/stanford-stages/inf_hypnodensity.py", line 119, in get_features
    X = self.Features.extract(self.hypnodensity[idx])
  File "/home/raghav/Development/stanford-stages/inf_hypnodensity.py", line 455, in extract
    I1 = (i for i, v in enumerate(rate) if v > 0.05).__next__()
StopIteration

```

Another similar EDF file that was encoded in the same way as this one processes fine. Is there a way to diagnose the problem?

This is the command I use:

```

python3 -W ignore inf_narco_app.py "$FILENAME" \
  '{"channel_indices":{"centrals":[5,6],"occipitals":[7,8],"eog_l":1,"eog_r":9,"chin_emg":11},
   "show":{"plot":false,"hypnodensity":false,"hypnogram":false,"diagnosis":true},
   "save":{"plot":true,"hypnodensity":true, "hypnogram":true,"diagnosis":true}
   }'

```

**Comment by informaton** [comment]
Hi, it looks like the issue you are encountering has to do with the narcolepsy diagnosis phase.  If you are not concerned about this, then you can skip this part by setting "diagnosis": false.  Otherwise, look at the inf_config.py file and verify that the narcolepsy classification path is correct.  If those match up, the next possibility is that there is an extensive flat-line segment (i.e. greater than 5 minutes) in your channels.   Yes, that appears to be the case here in the file you sent (starting around 2:40:30).  This leads to a divide by zero condition since one of the denominator values relies on a running calculation of 5 minutes of data, which turns out to be 0 in these excessive flat-line conditions.  

This is fixed in the _beta_ branch, but that is not so helpful to you right now since the beta branch does not work with the narcolepsy models here.  I'll try and get the same fix into the _manuscript_ branch.  These sections are removed from the feature extraction step for classifying narcolepsy.  The hypnodensity in these sections is all 0, which results in a hypnogram score of wake because of the way the Python works in selecting maximum values and how the hypnodensity columns map to the different sleep stage categories.

**Comment by RaghavRao** [comment]
Thank you.

For the sake of completeness, a different file also fails, most likely for the same reason:
named [Anna May0010-v2.edf](https://www.dropbox.com/sh/e58owb5ireh72i9/AAB8mkNgc9vk-BpsiMq1ex-Pa?dl=0)

I think the best move is for us to wait until for the fixes in the manuscript branch?

**Comment by informaton** [comment]
Thank you for this.  I'll take a look at it now, and see if it corrects with the update.

**Comment by informaton** [comment]
I posted the fix I mentioned earlier to the manuscript branch.  However, the real issue is actually the channel indices in your json configuration. They are all off by 1.  That is channel indices start at 0, not 1.  So the first channel, your Left EOG is at index 0, and so on for the others.  

I used the following configuration at first and did not run into any problems with the original code: 

    python3 -W ignore inf_narco_app.py "$FILENAME" \
      '{"channel_indices":{"centrals":[4,5],"occipitals":[6,7],"eog_l":0,"eog_r":8,"chin_emg":10},
       "show":{"plot":false,"hypnodensity":false,"hypnogram":false,"diagnosis":true},
       "save":{"plot":true,"hypnodensity":true, "hypnogram":true,"diagnosis":true}
       }'

There must be something odd about the other leads there were being used.  I suspect it is the 'Body' lead that was being referenced for the Right EOG, that likely gives prolonged 0's as one of its positions.
