### ISSUE TITLE
Error reading EDF+ Files

### ISSUE THREAD

**Issue by RaghavRao** [Stanford-STAGES/stanford-stages#29]
This may be an issue with pyedflib, but I was wondering if you guys have dealt with:

`OSError: the file is not EDF(+) or BDF(+) compliant (it contains format errors)`

**Comment by informaton** [comment]
Yes, we have come across those errors, particularly with pyedflib.  The
module is quite strict and will not process the files for any deviation
from the EDF specification.  One option is to download your own copy
version of pyedflib and then adjust the source code so that it does throw
errors for things you are fine with.  Another option is to update the EDF
and bring it into compliance.  EDFBrowser is a free tool that in our
experience provides a bit more information into what the exact format error
is and what to adjust.

**Comment by RaghavRao** [comment]
Thanks for the suggestion!
EDF Browser showed that the Version string contained a non ASCII character.

I suppose we could just batch rewrite the Version field?

**Comment by informaton** [comment]
Yes, that should do it.  The version string header field is quite specific and has different meanings for if you want EDF vs EDF+ continuous or discontinuous.  Sometimes software programs fill these fields in with integer values of 0 (null) instead of 32 (space).  It's particularly troublesome when it happens in header fields that are treated as plain text otherwise (e.g. the channel labels).  

You probably already have this, but for ease of reference here is a link to the [edf specification](https://www.edfplus.info/specs/edf.html).

**Comment by RaghavRao** [comment]
Thanks! Closing
